config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}

  devise_scope :user do
    get  'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'contents#index'
  
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'logout'
    end
  end

  resources :contents do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'ok'
    end
    member do
      get   'get_category_children', defaults: { format: 'json' }
      get   'get_category_grandchildren', defaults: { format: 'json' }
      post  'purchase'
      get   'purchased'
      get   'buy'
      get   'reserve'
      patch 'reserved'
      patch 'reserve_cancel'
    end
  end

  resources :cards, only: [:show, :new, :index, :create, :destroy] do
    collection do
      post 'pay'
    end
  end

  resources :categories, only: [:index, :show]
end

app/models/content.rb
class Content < ApplicationRecord
  enum size: {
    "XXS以下":1, "XS(SS)":2, "S":3, "M":4, "L":5, "XL(LL)":6, "2XL(3L)":7, "3XL(4L)":8, "4XL(5L)以上":9, "FREESIZE":10, "該当なし":11
  }
  enum status: {
    "新品・未使用":1, "未使用に近い":2, "目立った傷や汚れなし":3, "やや傷や汚れあり":4, "傷や汚れあり":5, "全体的に状態が悪い":6
  }
  enum postage: {
    "送料込み（出品者負担)":1, "着払い（購入者負担）":2
  }
  enum shipment: {
    "1〜２日で発送":1, "2〜3日で発送":2, "4〜7日で発送":3
  }
  enum prefecture: {
    "北海道":1, "青森県":2, "岩手県":3, "宮城県":4, "秋田県":5, "山形県":6, "福島県":7,
    "茨城県":8, "栃木県":9, "群馬県":10, "埼玉県":11, "千葉県":12, "東京都":13, "神奈川県":14,
    "新潟県":15, "富山県":16, "石川県":17, "福井県":18, "山梨県":19, "長野県":20,
    "岐阜県":21, "静岡県":22, "愛知県":23, "三重県":24,
    "滋賀県":25, "京都府":26, "大阪府":27, "兵庫県":28, "奈良県":29, "和歌山県":30,
    "鳥取県":31, "島根県":32, "岡山県":33, "広島県":34, "山口県":35,
    "徳島県":36, "香川県":37, "愛媛県":38, "高知県":39,
    "福岡県":40, "佐賀県":41, "長崎県":42, "熊本県":43, "大分県":44, "宮崎県":45, "鹿児島県":46, "沖縄県":47
  }

  belongs_to :category
  belongs_to :seller, class_name: "User", optional: true, foreign_key: "seller_id"
  belongs_to :buyer, class_name: "User", optional: true, foreign_key: "buyer_id"
  belongs_to :auction, class_name: "User", optional: true, foreign_key: "auction_id"
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, :explain, presence: true
  validates :price, presence: true, numericality: {
    only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999
  }
  validates :category_id, numericality: {
    only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 9999999
  }
  validates :images, presence: true

  scope :category, ->(category_id) {
    where(category_id: category_id).order(created_at: "DESC").limit(10)
  }
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  before_action :set_contents
  before_action :set_content,
    only: [:show, :destroy, :edit, :update, :buy]
  before_action :set_current_user_contents, :set_user, 
    only: [:p_transaction, :p_exhibiting, :p_soldout]
  before_action :content_category,
    only: [:edit, :update]

  def index
    @contents_list = Content.where(buyer_id: nil).limit(50).includes(:seller,:buyer,:auction,:images)
    unless @contents.length == 0
      pickup_category_content = Content.order("RAND()").find_by(buyer_id: nil)
      pickup_category_grandchild = Category.find(pickup_category_content.category_id)
      pickup_category_child = Category.find(pickup_category_grandchild.parent_id)
      @pickup_category = Category.find(pickup_category_child.ancestry)
      @contents_category = Content.where(category_id: @pickup_category.indirect_ids).where(buyer_id: nil).order("RAND()").limit(5).includes(:images)
      @pickup_brand_content = Content.order("RAND()").where.not(brand: "").find_by(buyer_id: nil)
      if @pickup_brand_content
        @contents_brand = Content.where(brand: @pickup_brand_content.brand).where(buyer_id: nil).order("RAND()").limit(5).includes(:images)
      end
    end
  end

  def show
    @contents_category = Content.where(category_id: @content.category_id).where(buyer_id: nil).order("RAND()").limit(3).includes(:images)
  end
  
  def new
    @category_parent_array = Category.where(ancestry: nil)
    if user_signed_in?
      @content = Content.new
      @content.images.build
    else
      redirect_to root_path
    end
  end

  def create
    @content = Content.new(content_params)
    @content.images.present?
    if @content.save
      redirect_to root_path
    else
      flash.now[:alert] = '必須項目を入力してください'
      @category_parent_array = Category.where(ancestry: nil)
      @content = Content.new
      @content.images.build
      render :new
    end
  end

  def destroy
    if @content.destroy
      redirect_to root_path, notice: '削除しました'
    else
      render :show
    end
  end

  def edit   
  end

  def update    
    if params[:content].keys.include?("image") || params[:content].keys.include?("images_attributes") 
      if @content.valid?
      # @content.images.ids.をeach処理で一つずつimageハッシュに存在するか確認、不在ならばdestroy。
        if params[:content].keys.include?("image") 
        # dbにある画像がedit画面で一部削除してるか確認
          update_images_ids = params[:content][:image].values #投稿済み画像 
          before_images_ids = @content.images.ids
          # 商品に紐づく投稿済み画像が、投稿済みにない場合は削除する
          before_images_ids.each do |before_img_id|
            Image.find(before_img_id).destroy unless update_images_ids.include?("#{before_img_id}") 
          end
        else
          before_images_ids = @content.images.ids
          before_images_ids.each do |before_img_id|
            Image.find(before_img_id).destroy 
          end
        end

        @content.update(content_params)
        
        redirect_to content_path(@content.id), notice: "商品を更新しました"
        
      else
        render 'edit'
      end

    else
      redirect_to content_path(@content.id),
        alert: '画像が選択されていないので変更がキャンセルされました'
      # redirect_back(fallback_location: root_path, alert: '画像を選択してください')
    end
  end

  def get_category_children
    @category_children = Category.find("#{params[:parent_id]}").children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def buy
    @card = Card.find_by(user_id: current_user.id) if Card.find_by(user_id: current_user.id).present?
    if @card.present? && !(@content.seller_id == current_user.id) && @content.buyer_id.nil?
      Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_info = customer.cards.data.first
    else
      if @card.blank?
        flash[:alert] = 'カードを登録してください'
        redirect_to controller: "cards", action: "new"
      else
        flash[:alert] = 'その商品は存在しません'
        redirect_to root_path
      end
    end
  end

  def ok
    @content = Content.where(buyer_id: current_user.id).order('updated_at DESC').first
    
    # エラーハンドリング
    # プロダクトが存在しない、または現在の時刻と商品のアップ日時が5分離れている場合トップへリダイレクト
    if @content.blank? || (Time.zone.now - @content.updated_at) / 60 > 5
        flash[:alert] = 'ページの有効期限が切れてます'
        redirect_to root_path
    end

  end

  #出品中のアクション
  def p_exhibiting
  end

  #取引中のアクション
  def p_transaction
  end

  #売却済みのアクション
  def p_soldout
  end

  private
  def content_params
    params.require(:content).permit(
      :name, :category_id, :price, :explain,
      :size, :brand, :status, :postage, :shipment, :prefecture,
      images_attributes: [:content_image, :id, :_destroy]
    ).merge(seller_id: current_user.id)
  end

  def set_content
    @content = Content.find(params[:id])
  end

  def content_category
    @grandchild = @content.category
    @child = @grandchild.parent
    @category_parent_array = Category.where(ancestry: nil)
    @category_child_array = Category.where(ancestry: @child.ancestry)
    @category_grandchild_array = Category.where(ancestry: @grandchild.ancestry)
  end

  def set_contents
    @contents = Content.all.includes(:seller, :buyer, :auction, :images)
  end

  def set_current_user_contents
    if user_signed_in? 
      @contents = current_user.contents.includes(:seller, :buyer, :auction, :images)
    else
      redirect_to new_user_session_path
    end
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
  def explanation_placeholder
    <<-"EOS".strip_heredoc
      商品の説明（色、素材、重さ、定価、注意点など）
      
      例）・2010年頃に1万円で購入したジャケット
      　　・ライトグレーで傷はあり
      　　・あわせやすいのでおすすめ！
    EOS
  end
end

app/views/contents/_app_banner.html.haml
%aside.AppBanner
  .BannerInner
    %h2.BannerInner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.BannerInner__text
      今すぐ無料ダウンロード！
    .BannerInner__icon
      = link_to "#" do
        = image_tag "app-store.svg", class: "BannerInner__icon"
      = link_to "#" do
        = image_tag "google-play.svg", class: "BannerInner__icon"

app/views/contents/_card_registration.html.haml
.credit-update
  .credit-update__label
    クレジットカード情報入力
  .card-form
    .card-form__box
      = form_tag(cards_path, method: :post, id: 'charge-form', name: "inputForm") do |f|
        .card-form__box__number
          %label{class:'box-group--label', for: 'card_number'} カード番号
          %span.input-require
            必須
          = text_field_tag "number", "", class: 'card-number--input', type: "text", id: 'card_number', maxlength: "16", placeholder: "半角数字のみ"
          .registration-error{type: "hidden", value: "必須項目です"}
          %ul.card-list
            -# assets/imagesにimageを設置しており、それをimage_tagで呼び出しています。
            %li.card-list--item{ style: "margin-left: 0;"}
              = image_tag "visa.svg", width:"49", height:"20"
            %li.card-list--item
              = image_tag "master-card.svg", width:"34", height:"20"
            %li.card-list--item  
              = image_tag "saison-card.svg", width:"30", height:"20"
            %li.card-list--item  
              = image_tag "jcb.svg", width:"32", height:"20"
            %li.card-list--item
              = image_tag "american_express.svg", width:"21", height:"20"
            %li.card-list--item
              = image_tag "dinersclub.svg", width:"32", height:"20"
            %li.card-list--item 
              = image_tag "discover.svg", width:"32", height:"20"

        .card-form__box__expire
          %label.box-group--label 有効期限
          %span.input-require
            必須
          .card-expire
            .card-expire__select-month
              %select#exp_month{name: "exp_month", type: "text"}
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %i.card-form-expire-icon
                = image_tag "arrow-bottom.png", size:"16x10",class:"arrow-bottom-icon5"
              %span{class: "month"} 月
            .card-expire__select-year
              %select#exp_year{name: "exp_year", type: "text"}
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %i.card-form-expire-icon
                = image_tag "arrow-bottom.png", size: "16x10",class:"arrow-bottom-icon6"
              %span{class:"year"} 年

        .card-form__box__security-code
          %label.box-group--label{for: "cvc"} セキュリティーコード
          %span.input-require
            必須
          = text_field_tag "cvc", "", class: 'payment__security-code', type: "text", id: "cvc", maxlength: "4" ,placeholder: "カード背面４桁もしくは３桁の番号"
          .question-form
            %span.question-form__mark ?
            %span.question-form__text 
              カード裏面の番号とは？
        #card_token
        = submit_tag "追加する", class: "card-form__box__add", id: "token_submit", type: 'button'

app/views/contents/_footer.html.haml
%footer
  %ul.Footer__contents
    %li.Content
      %h2.Content__head FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社）", "#"
        %li
          = link_to "プライバシーポリシー", "#"
        %li
          = link_to "FURIMA利用規約", "#"
        %li
          = link_to "ポイントに関する特約", "#"
    %li.Content
      %h2.Content__head FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧", "#"
        %li
          = link_to "ブランド一覧", "#"
    %li.Content
      %h2.Content__head ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド", "#"
        %li
          = link_to "FURIMAロゴ利用ガイドライン", "#"
        %li
          = link_to "お知らせ", "#"
  .Footer__logo
    = link_to "#" do
      = image_tag "logo-white.png"
  %p © FreeMerge

app/views/contents/_header.html.haml
%header
  .HeaderItems
    = link_to image_tag("logo.png", class: "HeaderLogo"), root_path
    %input.SearchForm{:name => "keyword", :placeholder => "キーワードから探す", :type => "text"}/
    %button.SearchBtn{:name => "btn", :placeholder => "検索", :type => "submit"}
      = image_tag "icon-search1.png", class: "BtnImage"
  .HeaderInfo
    .ContentGroup
      =link_to "カテゴリー", root_path, class: "Categorie"
      =link_to "ブランド", root_path, class: "Brand"
    .LoginSignin
      -if current_user
        =link_to "マイページ","/users/#{current_user.id}", class: "Mypage"
      -else
        =link_to "ログイン", new_user_session_path, class: "Login"
        =link_to "新規会員登録", new_user_registration_path, class: "Signin"

app/views/contents/_purchase_btn.html.haml
= link_to new_content_path do
  .PurchaseBtn
    %span.PurchaseBtn__text
      出品する
      = image_tag "icon_camera.png", class: "PurchaseBtn__icon", data: {"turbolinks" => false}

app/views/contents/buy.html.haml
.Main
  .ContentsNew
    .ContentsNew__topWrapper
      = link_to root_path do
        = image_tag "logo.png", class: "TopIcon"
    .ContentsNew__middleWrapper
      .ExhibitionForm
        .ExhibitionForm__normal
          .ExhibitionForm__body
            %h2.BuyInfo
              購入内容の確認
            .Error
        %hr/
    .ContentsNew__middleWrapper
      .ExhibitionForm
        .ExhibitionForm__normal
          .ExhibitionForm__body
            .ContentInfo
              .ContentImage

                = image_tag(@content.images[0].content_image.url, class: "BuyContent")
              .ContentName
                = @content.name
              .Content__cost
                = "#{@content.postage}(税込)"
                %span
                  = number_to_currency(@content.price, unit: "円", strip_insignificant_zeros: true)
            .Error
        %hr/
    .ContentsNew__middleWrapper
      .ExhibitionForm
        .ExhibitionForm__normal
          .ExhibitionForm__body
            .PriceInfo
              .PriceInfo__name
                支払い金額
              .PriceInfo__cost
                = number_to_currency(@content.price, unit: "円", strip_insignificant_zeros: true)
            .Error
        %hr/
    .ContentsNew__middleWrapper
      .ExhibitionForm
        .ExhibitionForm__normal
          .ExhibitionForm__body
            .Payment
              .Payment__method
                支払い方法
              .Payment__registration
                %section.creditcard_section
                  - if @card_info.blank?
                    %i.fas.fa-plus-circle
                    %span.icon-register
                    = link_to "登録してください", new_card_path
                  - else
                    = "**** **** **** " + @card_info.last4
                    - exp_month = @card_info.exp_month.to_s
                    - exp_year = @card_info.exp_year.to_s.slice(2,3)
                    = exp_month + " / " + exp_year
            .Error
        %hr/
    .ContentsNew__middleWrapper
      .ExhibitionForm
        .ExhibitionForm__normal
          .BuyBtn
            = link_to "購入する", {controller: "cards", action: "pay", content_id: @content}, method: :post, class:"BuyButton"

    .ContentsNew__bottomWrapper
      = link_to root_path do
        = image_tag "logo.png", class: "BottomIcon"

app/views/contents/edit.html.haml
.Main
  .ContentsNew
    .ContentsNew__topWrapper
      = link_to root_path do
        = image_tag "logo.png", class: "TopIcon"
    .ContentsNew__middleWrapper
      = form_with model: @content do |f|
        .ExhibitionForm
          .ExhibitionForm__normal
            %p.FormTitle
              商品
            .ExhibitionForm__body.NotFirstChild
              .PhotosTop
                .PhotosTop__text
                  %label
                    出品画像
                  %span.Required
                    必須
                .PhotosMiddle
                  %p.PhotosMiddle__text
                    最大5枚までアップロードできます
                  .clearfix
                    // 写真のプレビューとインプットボタンのul
                    %ul#previews
                      = f.fields_for :image do |image|
                        - @content.images.each_with_index do |img, i|
                          %li.image-preview
                            %label.upload-label{style:"display: none;"}
                              .upload-label__text
                                ドラッグ ＆ ドロップ
                                %br
                                またはクリックしてファイルをアップロード
                                .input-area
                                  = image.file_field :name, value: img.content_image ,class: "hidden image_upload"
                                  = image.hidden_field :id, value: img.id, name:"content[image][#{i}]"
                            .image-preview__wapper
                              = image_tag img.content_image.to_s, class:"preview"
                            .image-preview_btn
                              .image-preview_btn_delete 削除
          .ExhibitionForm__normal
            .ExhibitionForm__body
              .TitleTop
                .TitleTop__text
                  %label
                    商品名
                  %span.Required
                    必須
                .TitleBottom
                  = f.text_field :name, class: 'FormBox', placeholder: '40字まで'
              .Error
            .ExhibitionForm__body.NotFirstChild
              .ExplanationTop
                .ExplanationTop__text
                  %label
                    商品の説明
                  %span.Required
                    必須
                .ExplanationBottom
                  =f.text_area :explain,class:"TextArea",placeholder: explanation_placeholder
              .ExplanationCounter
                0/1000
              .Error
          %hr/
          .ExhibitionForm__normal
            %p.FormTitle
              商品の詳細
            .ExhibitionForm__body.NotFirstChild
              .CategoryTop
                .CategoryTop__text
                  %label
                    カテゴリー
                  %span.Required
                    必須
              .CategoryBottom{id: "category__box--parent"}
                = f.collection_select :category_id, @category_parent_array, :id, :name,{prompt:"選択して下さい",selected:@grandchild.root_id},{class:"FormBox"}
                //子カテゴリ
                = f.collection_select :category_id, @category_child_array, :id, :name,{prompt:"選択して下さい",selected:@grandchild.parent_id},{class:"FormBox childcategorys", id: "child__category"}
                = f.collection_select :category_id, @category_grandchild_array, :id, :name,{prompt:"選択して下さい"},{class:"FormBox childcategorys", id: "grandchild__category"}
              .Error
            .ExhibitionForm__body.NotFirstChild#SizeBox
              .CategoryTop
                .CategoryTop__text
                  %label
                    サイズ
                  %span.Required
                    必須
              .CategoryBottom
                = f.select :size, Content.sizes.keys,{prompt:"選択して下さい"},{class:"FormBox"}
              .Error
            %hr/
            .ExhibitionForm__body.NotFirstChild
              .CategoryTop
                .CategoryTop__text
                  %label
                    ブランド
                  %span.Any
                    任意
              .CategoryBottom
                = f.text_field :brand, class: 'FormBox', placeholder: '例）LOUIS VUITTON'
            .ExhibitionForm__body.NotFirstChild
              .CategoryTop
                .CategoryTop__text
                  %label
                    商品の状態
                  %span.Required
                    必須
              .CategoryBottom
                = f.select :status, Content.statuses.keys,{prompt:"選択して下さい"},{class:"FormBox"}
              .Error
          %hr/
          .ExhibitionForm__normal
            %p.FormTitle
              配送について
            .ExhibitionForm__body.NotFirstChild
              .PostageTop
                .PostageTop__text
                  %label
                    発送料の負担
                  %span.Required
                    必須
              .PostageBottom
                = f.select :postage, Content.postages.keys,{prompt:"選択して下さい"},{class:"FormBox"}
              .Error
            .ExhibitionForm__body.NotFirstChild
              .ShippingAreaTop
                .ShippingAreaTop__text
                  %label
                    発送元の地域
                  %span.Required
                    必須
              .ShippingAreaBottom
                = f.select :prefecture, Content.prefectures.keys,{prompt:"選択して下さい"},{class:"FormBox"}
              .Error
            .ExhibitionForm__body.NotFirstChild
              .DaysUntilShippingTop
                .DaysUntilShippingTop__text
                  %label
                    発送までの日数
                  %span.Required
                    必須
              .DaysUntilShippingBottom
                = f.select :shipment, Content.shipments.keys,{prompt:"選択して下さい"},{class:"FormBox"}
              .Error
          %hr/
          .ExhibitionForm__normal
            %p.FormTitle
              価格（¥300〜¥9,999,999）
            .ExhibitionForm__body.NotFirstChild
              .PriceBody
                .PriceLeft
                  .PriceTop__text
                    %label
                      販売価格
                    %span.Required
                      必須
                .PriceRight
                  %h3
                    ¥
                  = f.text_field :price, class: 'FormBox', placeholder: '0'
              .Error
          .ExhibitionForm__exhibition
            = f.submit "編集する", class: "ExhibitionBtn"
            .Return
              = link_to content_path(@content.id), class: "ReturnBtn" do
                戻る
          .ExhibitionForm__precautions
            %p.PrecautionsText
              禁止されている行為および出品物を必ずご確認ください。
              %br
              偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。
    .ContentsNew__bottomWrapper
      = link_to root_path do
        = image_tag "logo.png", class: "BottomIcon"

app/views/contents/ok.html.haml
= render partial: "contents/header"
.Main
  .mypage_a
    %main.mypage-contents.clearfix
      .main-content
        %section.user
          .user-link
            %figure
              .user-link__iconn
                購入が完了しました
          .return-top
            = link_to root_path do
              トップへ戻る
      = render "users/show_side"
  = render partial: "contents/app_banner"
  = render partial: "contents/purchase_btn"
= render partial: "contents/footer"

app/views/contents/show.html.haml
= render "header"

.Main
  .ShowMain
    .ContentRight
      .TopContent
        .ItemBox
          %h2.ItemBox__name
            = @content.name
          .ItemBox__body
            %ul
              %li
                .ItemBox__body--main
                  = image_tag(@content.images[0].content_image.url)
                  - if @content.buyer_id?
                    .SoldLabel
                      SOLD
                %ul
                  %li
                    - if @content.images[1].present?
                      .ItemBox__body--sub
                        = image_tag(@content.images[1].content_image.url)
                        - if @content.buyer_id?
                          .SoldLabel
                            SOLD
                  %li
                    - if @content.images[2].present?
                      .ItemBox__body--sub
                        = image_tag(@content.images[2].content_image.url)
                        - if @content.buyer_id?
                          .SoldLabel
                            SOLD
                  %li
                    - if @content.images[3].present?
                      .ItemBox__body--sub
                        = image_tag(@content.images[3].content_image.url)
                        - if @content.buyer_id?
                          .SoldLabel
                            SOLD
                  %li
                    - if @content.images[4].present?
                      .ItemBox__body--sub
                        = image_tag(@content.images[4].content_image.url)
                        - if @content.buyer_id?
                          .SoldLabel
                            SOLD
          .ItemBox__price
            %span
              = number_to_currency(@content.price, unit: "円", strip_insignificant_zeros: true)
            .ItemBox__priceDetail
              - if @content.postage == "送料込み（出品者負担)"
                %h3 （税込）送料込み
              - elsif @content.postage == "着払い（購入者負担）"
                %h3 （税込）着払い
          .ItemBox__detail
            = @content.explain
          .ItemBox__table
            %table
              %tr
                %th 出品者
                %td
                  = @content.seller.nickname
              %tr
                %th カテゴリー
                %td
                  #{@content.category.parent.parent.name} / #{@content.category.parent.name} / #{@content.category.name}
              %tr
                %th ブランド
                %td
                  = @content.brand
              %tr
                %th 商品のサイズ
                %td
                  = @content.size
              %tr
                %th 商品の状態
                %td
                  = @content.status
              %tr
                %th 配送料の負担
                %td
                  = @content.postage
              %tr
                %th 発送元の地域
                %td
                  = @content.prefecture
              %tr
                %th 発送日の目安
                %td
                  = @content.shipment
          .ItemBox__optionalArea
            %ul
              %li
                %button{type: "button", class:'btn'}
                  お気に入り 0
            %ul
              %li
              = link_to "#", class: "report" do
                不適切な商品の通報
          - if @content.buyer_id?
            .ItemBox__soldout
              .SoldOutBtn
                売り切れ
          - else
            - if user_signed_in? && current_user.id != @content.seller_id
              .ItemBox__buy
                = link_to "購入情報の確認", buy_content_path(@content.id), method: :get, class:"BuyConfirmationBtn"
            - if user_signed_in? && current_user.id == @content.seller_id
              .ItemBox__edit
                = link_to "編集する", edit_content_path(@content.id), method: :get, class:"editBtn"
              .ItemBox__delete
                = link_to "削除する", content_path(@content.id), method: :delete, class:"deleteBtn"
        .CommentBox
          = form_with(id: "new_comment") do |f|
            = f.text_area :content, class: 'commentbody'
            %p.noticeMsg
              相手のことを考え丁寧なコメントを心がけましょう。
              %br
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
          %button.commentBtn{type: 'submit', name: 'button'}
            コメントする
      .Links
        = link_to '#',class: 'links__left' do
          < 前の商品
        = link_to '#',class: 'links__right' do
          後ろの商品 >
      .RelatedItems
        = link_to '#',class: 'RelatedItems__body' do
          #{@content.category.parent.parent.name} / #{@content.category.parent.name} / #{@content.category.name} をもっと見る
        .ContentLists
          - @contents_category.each do |content|
            .ContentList
              = link_to content_path(content) do
                = image_tag content.images[0].content_image.url, height: '150px', width: '100%'
              .ContentList__body
                %h3.name
                  = content.name
                .Details
                  %ul
                    %li
                      = number_to_currency(content.price, unit: "円", strip_insignificant_zeros: true)
                    %li
                      = icon('fa', 'star')
                      0
                  %p (税込)

  = render "app_banner"
  = render "purchase_btn"
= render "footer"