config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}

  devise_scope :user do
    get  'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'contents#index'
  
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'logout'
    end
  end

  resources :contents do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'ok'
    end
    member do
      get   'get_category_children', defaults: { format: 'json' }
      get   'get_category_grandchildren', defaults: { format: 'json' }
      post  'purchase'
      get   'purchased'
      get   'buy'
      get   'reserve'
      patch 'reserved'
      patch 'reserve_cancel'
    end
  end

  resources :cards, only: [:show, :new, :index, :create, :destroy] do
    collection do
      post 'pay'
    end
  end

  resources :categories, only: [:index, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :address
  has_one :card
  has_many :saling_items, -> { where("seller_id is not NULL && buyer_id is NULL") }, class_name: "Product"
  has_many :sold_items, -> { where("seller_id is not NULL && buyer_id is not NULL") }, class_name: "Product"
  # has_many :auction_items, -> { where("seller_id is not NULL && auction_id is not NULL && buyer_id is NULL") }, class_name: "Product"
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :birthday, presence: true
  validates :nickname, presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      render :new and return
    end
  
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address and return
  end
  
  def new_address
  end
  
  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    sign_in(:user, @user)
    redirect_to root_path
  end
  
  protected
  
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(
      :sign_up, keys:[
        :nickname, :birthday, :first_name, :last_name,
        :ship_first_name_kana, :ship_family_name_kana
      ]
    )
  end
  
  def address_params
    params.require(:address).permit(
      :postal_code, :prefecture, :prefecture_id,
      :city, :address, :apartment
    )
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_show_side.html.haml
.side-content
  %nav.mypage-nav
    %ul.mypage-nav-list
      %li
        =link_to "/users/#{current_user.id}", class: "mypage-nav-list-item" do
          マイページ
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          お知らせ（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          やることリスト（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          いいね！一覧（未実装）
          %i.icon-arrow-right
      %li
        =link_to new_content_path, class: "mypage-nav-list-item" do
          出品する
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          出品した商品 - 出品中（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          出品した商品 - 取引中（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          出品した商品 - 売却済み（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          購入した商品 - 取引中（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          購入した商品 - 過去の取引（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          ニュース一覧（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          評価一覧（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          ガイド（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          お問い合わせ（未実装）
          %i.icon-arrow-right
    %h3.mypage-nav-head-merpay メルペイ
    %ul.mypage-nav-list-merpay
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          売上・振込申請（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          ポイント（未実装）
          %i.icon-arrow-right
    %h3.mypage-nav-head-setting 設定
    %ul.mypage-nav-list-setting
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          プロフィール（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          発送元・お届け先住所変更（未実装）
          %i.icon-arrow-right
      %li
        =link_to cards_path, class: "mypage-nav-list-item" do
          支払い方法
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          メール/パスワード
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          本人情報
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          電話番号の確認（未実装）
          %i.icon-arrow-right
      %li
        =link_to logout_user_path(current_user.id), class: "mypage-nav-list-item" do
          ログアウト
          %i.icon-arrow-right

app/views/users/logout.html.haml
= render partial: "contents/header"
.Main
  .mypage_a  
    %main.mypage-contents.clearfix
      .main-content
        .Contentt
          .Contentt__form
            = link_to  destroy_user_session_path, class: "destroy", method: :delete do
              ログアウト
      = render "show_side"
  = render partial: "contents/app_banner"
  = render partial: "contents/purchase_btn"
= render partial: "contents/footer"

app/views/users/show.html.haml
= render partial: "contents/header"

.Main
  .ShowMypage
    .main-content
      %section.user
        .user-link
          %figure
            .user-link__iconn
              = image_tag "member_photo_noimage_thumb.png", class:"user-link__icon"
          %h2.user-link__name
          .user-link__number
            評価  0  出品数  0

      %section.transaction
        .transaction-history
          %ul.transaction-history-tabs
            .transaction-history-tabs_select
              やることリスト
            .transaction-history-tabs_li
              お知らせ
          %ul.transaction-history-content
            %li.tab-content-transaction__notfound
              現在、やることリストはありません

        .transaction-history
          %h2.transaction-history-header
            購入した商品
          %ul.transaction-history-tabs
            .transaction-history-tabs_select
              取引中
            .transaction-history-tabs_li
              過去の取引
          %ul.transaction-history-content
            %li.tab-content-transaction__notfound
              取引中の商品がありません

    = render partial: "users/show_side"  
  = render partial: "contents/app_banner"
  = render partial: "contents/purchase_btn"
= render partial: "contents/footer"

app/views/users/show_side.html.haml
.side-content
  %nav.mypage-nav
    %ul.mypage-nav-list
      %li
        =link_to "/users/#{current_user.id}", class: "mypage-nav-list-item" do
          マイページ
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          お知らせ（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          やることリスト（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          いいね！一覧（未実装）
          %i.icon-arrow-right
      %li
        =link_to new_content_path, class: "mypage-nav-list-item" do
          出品する
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          出品した商品 - 出品中（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          出品した商品 - 取引中（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          出品した商品 - 売却済み（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          購入した商品 - 取引中（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          購入した商品 - 過去の取引（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          ニュース一覧（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          評価一覧（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          ガイド（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          お問い合わせ（未実装）
          %i.icon-arrow-right
    %h3.mypage-nav-head-merpay メルペイ
    %ul.mypage-nav-list-merpay
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          売上・振込申請（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          ポイント（未実装）
          %i.icon-arrow-right
    %h3.mypage-nav-head-setting 設定
    %ul.mypage-nav-list-setting
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          プロフィール（未実装）
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          発送元・お届け先住所変更（未実装）
          %i.icon-arrow-right
      %li
        =link_to cards_path, class: "mypage-nav-list-item" do
          支払い方法
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          メール/パスワード
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          本人情報
          %i.icon-arrow-right
      %li
        =link_to "#", class: "mypage-nav-list-unimplemented" do
          電話番号の確認（未実装）
          %i.icon-arrow-right
      %li
        =link_to logout_user_path(current_user.id), class: "mypage-nav-list-item" do
          ログアウト
          %i.icon-arrow-right