config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}

  devise_scope :user do
    get  'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'contents#index'
  
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'logout'
    end
  end

  resources :contents do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'ok'
    end
    member do
      get   'get_category_children', defaults: { format: 'json' }
      get   'get_category_grandchildren', defaults: { format: 'json' }
      post  'purchase'
      get   'purchased'
      get   'buy'
      get   'reserve'
      patch 'reserved'
      patch 'reserve_cancel'
    end
  end

  resources :cards, only: [:show, :new, :index, :create, :destroy] do
    collection do
      post 'pay'
    end
  end

  resources :categories, only: [:index, :show]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require 'payjp'

  before_action :set_card
  before_action :set_secretkey, only: [:index, :create, :destroy, :pay]

  # 以前にカード情報を登録していた場合、以前の登録カード情報を表示する
  def index
    @cards = Card.all
    if @card
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_info = customer.cards.data.first
      set_card_brand(@card_info.brand)
    end
  end

  # クレジットカード情報入力画面
  def new
    redirect_to action: "index" if @card.present?
  end

  # 登録画面で入力した情報をDBに保存
  def create
    if params['payjp-token'].blank?
      flash[:alert] = 'クレジットカードを登録できませんでした'
      redirect_to action: "new"
    else

      # ここで先ほど生成したトークンを顧客情報と紐付け、PAY.JP管理サイトに送信
      customer = Payjp::Customer.create(card: params['payjp-token'])
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "index"
      else
        redirect_to action: "create"
      end
    end
  end

  def destroy
    if !@card.blank? && @card.user_id == current_user.id
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      flash[:notice] = 'カードが削除されました'
      redirect_to action: "index"
    else
      flash[:alert]  = 'カードが削除されませんでした'
      redirect_to action: "index"
    end
  end

  def pay
    content = Content.find(params[:content_id])
    if @card.present? && @card.user_id == current_user.id && content.buyer_id.nil?
      if Payjp::Charge.create(amount: content.price, customer: @card.customer_id, currency: 'jpy') && content.update(buyer_id: current_user.id)
        redirect_to ok_contents_path
      else
        flash[:alert]  = 'サーバーでエラーが生じました'
        redirect_to root_path
      end
    else
      flash[:alert]  = 'カード情報を登録して下さい'
      redirect_to root_path
    end
  end

  private
  def set_card
    @card = Card.find_by(user_id: current_user.id) if Card.find_by(user_id: current_user.id).present?
  end

  def set_secretkey
    Payjp.api_key = Rails.application.credentials[:payjp_access_key]
  end

  def set_card_brand(brand)
    case brand
    when "Visa"
      @card_src = "card/visa.svg"
      @card_alt = "visa"
    when "JCB"
      @card_src = "card/jcb.svg"
      @card_alt = "jcb"
    when "MasterCard"
      @card_src = "card/master-card.svg"
      @card_alt = "mastercard"
    when "American Express"
      @card_src = "card/american_express.svg"
      @card_alt = "amex"
    when "Diners Club"
      @card_src = "card/dinersclub.svg"
      @card_alt = "dinersclub"
    when "Discover"
      @card_src = "card/discover.svg"
      @card_alt = "discover"
    end
  end
  
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/index.html.haml
= render partial: "contents/header"
.Main
  .mypage_a
    %main.mypage-contents.clearfix
      = render partial: "users/show_side"
      .Chapter
        .Chapter__title
          支払い方法
        .Chapter__inner
          %section
            .Chapter__inner__content
              クレジットカード
          - if @card_info
            - exp_month = sprintf("%02d", @card_info.exp_month )
            - exp_year = @card_info.exp_year.to_s.slice(2,3)
            %ul.settings-payment-list
              %li
                .right-single-content
                  %figure
                    = image_tag @card_src, alt: @card_alt, height: '30', width: '39'
                  .settings-payment-num= "**** **** **** " + @card_info.last4
                  .settings-payment-num= exp_month + " / " + exp_year
                  = link_to "削除する", card_path(@card), class: "settings-payment-remove" , method: :delete
          - else
            %section.Chapter__inner__add
              .Chapter__inner__add__btn
                = icon("fas", "plus-circle", class: "icon-card")
                = link_to "新規カードを登録する", new_card_path , class: "card-btn"
          .Chapter__inner__note
            = link_to "#", class: "inner-note" do
              支払い方法について ＞
      
  = render partial: "contents/app_banner"
  = render partial: "contents/purchase_btn"
= render partial: "contents/footer"

app/views/cards/new.html.haml
= render partial: "contents/header"
.Main
  .mypage_a
    %main.mypage-contents.clearfix
      = render partial: "users/show_side"
      .Chapter
        .Chapter__title
          クレジットカード情報入力
        .Chapter__credit
          .C-content
            .C-content__credit-card
              = form_with url: cards_path, method: :post, html: { name: "inputForm" }, class:"essential", local: true do |f|
                .essential__box
                  %span.essential__box__label
                    カード番号
                  %span.essential__box__need
                    必須
                = f.text_field :card_number, type: "text", class: "input-number", placeholder: "半角数字のみ 16桁", maxlength: "16", id: "card_number", pattern: "\d{16}"
                %ul.card-list
                  %li.card-list__icon
                    = image_tag "card/card-01_visa.svg", height: "30", width: "45"
                  %li.card-list__icon
                    = image_tag "card/card-02_master-card.svg", height: "30", width: "45"
                  %li.card-list__icon
                    = image_tag "card/card-03_saison-card.svg", height: "30", width: "45"
                  %li.card-list__icon
                    = image_tag "card/card-04_jcb.svg", height: "30", width: "45"
                  %li.card-list__icon
                    = image_tag "card/card-05_american_express.svg", height: "30", width: "45"
                  %li.card-list__icon
                    = image_tag "card/card-06_diners.svg", height: "30", width: "45"
                  %li.card-list__icon
                    = image_tag "card/card-07_discover.svg", height: "30", width: "45"

                .cards-expire
                  .essential__box
                    %span.essential__box__label
                      有効期限
                    %span.essential__box__need
                      必須
                    %br

                  .cards-expire__wrap
                    .cards-expire__wrap__item
                      = f.select :exp_month, [["01", 1], ["02", 2], ["03", 3], ["04", 4], ["05", 5], ["06", 6], ["07", 7], ["08", 8], ["09", 9], ["10", 10], ["11", 11], ["12", 12]], {}, class: "month", id: "exp_month"
                      = icon("fas", "angle-down", class:"inputSelect")
                      %span.expire-text
                        月
                      
                    .cards-expire__wrap__item
                      = f.select :exp_year, [["20", 2020], ["21", 2021], ["22", 2022], ["23", 2023], ["24", 2024], ["25", 2025], ["26", 2026], ["27", 2027], ["28", 2028], ["29", 2029]], {} , class: "year", id: "exp_year"
                      = icon("fas", "angle-down", class:"inputSelect")
                      %span.expire-text
                        年

                .cards-expire
                  .essential__box
                    %span.essential__box__label
                      セキュリティコード
                    %span.essential__box__need
                      必須
                  = f.text_field :cvc, type: "text", class: "input-number", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"

                .c-content-bottom#card_token
                  = f.submit "登録する", class: "c-content-bottom__add-btn", id: "token_submit"
      
  = render partial: "contents/app_banner"
  = render partial: "contents/purchase_btn"
= render partial: "contents/footer"